# Generated by Django 5.1.2 on 2024-10-30 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(editable=False, max_length=30, unique=True)),
                ('ranking_points', models.IntegerField(default=1000)),
                ('ranking_position', models.IntegerField(editable=False, unique=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('castle_1', models.CharField(choices=[('heaven', 'heaven'), ('inferno', 'inferno'), ('necropolis', 'necropolis'), ('sylvan', 'sylvan'), ('dungeon', 'dungeon'), ('academy', 'academy'), ('fortress', 'fortress'), ('stronghold', 'stronghold')], default='heaven', max_length=20)),
                ('castle_2', models.CharField(choices=[('heaven', 'heaven'), ('inferno', 'inferno'), ('necropolis', 'necropolis'), ('sylvan', 'sylvan'), ('dungeon', 'dungeon'), ('academy', 'academy'), ('fortress', 'fortress'), ('stronghold', 'stronghold')], default='heaven', max_length=20)),
                ('points_change', models.IntegerField(editable=False)),
                ('player_1', models.ForeignKey(blank=True, db_column='player_1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_as_player_1', to='h5_backend.player')),
                ('player_2', models.ForeignKey(blank=True, db_column='player_2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_as_player_2', to='h5_backend.player')),
                ('who_won', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_who_won', to='h5_backend.player')),
            ],
        ),
    ]
