# Generated by Django 5.1.2 on 2024-10-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h5_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='ranking_position',
            field=models.IntegerField(unique=True),
        ),
    ]
