# Generated by Django 5.1.2 on 2024-10-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h5_backend', '0002_alter_player_nickname_alter_player_ranking_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ranking_position',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
