# Generated by Django 5.1.2 on 2024-10-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h5_backend', '0004_alter_player_ranking_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='points_change',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
